

services:
    reverseproxy:
        build: reverseproxy
        ports:
            - 8080:8080
        restart: always

    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        command: [ "/bin/bash", "-c", "npm run dev" ]
        depends_on:
            - reverseproxy
        restart: always
        volumes:
            - ./frontend/frontend:/frontend

    backend:
        depends_on:
            - reverseproxy
        command:
            [
                "/bin/bash",
                "-c",
                "uvicorn app.main:app --reload --host 0.0.0.0 --port 4000"
            ]
        build: backend
        restart: always
        volumes:
            - ./backend/src:/backend/app
