

services:
    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./
        command: [ "/bin/bash", "-c", "npm run dev" ]
        restart: always
        volumes:
            - ./frontend:/frontend

    backend:
        command:
            [
                "/bin/bash",
                "-c",
                "uvicorn app.main:app --reload --host 0.0.0.0 --port 4000"
            ]
        build: backend
        restart: always
        volumes:
            - ./backend/src:/backend/app
