version: '3.8'

services:
  backend:
    ports:
      - "8888:8888"
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: /start-reload.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    command: npm run dev -- --host
